#!/usr/bin/env python3
"""gen_debug_terrain.py — OFFLINE bake of the D.7 placeholder terrain + tree
billboard INPUT geometry to a committed FLASH-CONST header
(src/demo/debug_terrain_gen.h).

WHY (integration gate, target-SRAM only): the placeholder input geometry was
computed into static buffers at init, so s_terrain_vtx/idx + s_tree_vtx/idx
lived in .bss (RAM) ~13 KB and overflowed the RP2040 RAM region when D.7 merged
with the other lanes. It is static deterministic data — bake it to const flash
arrays (like camera_path_gen.h / assets_gen) so it leaves .bss entirely; the
demo submits LOAD_VERTS/DRAW_TRIS pointers straight at the flash arrays.

The runtime demo_terrain_geometry/demo_tree_geometry FILL functions stay (host
tests + the T0 D.1 swap seam still want a fill API), but the renderer_demo /
the committed path use these const arrays. This generator reproduces the C fill
math EXACTLY (positions, per-cell debug colors, indices, winding) so all the
determinism / debug-color-histogram / near-plane guards keep passing.

Build does NOT run Python; debug_terrain_gen.h is committed data. Regenerate
when the placeholder layout changes:

    python3 src/demo/gen_debug_terrain.py src/demo/debug_terrain_gen.h
"""

import os
import sys

# ---- layout constants (MUST mirror src/demo/demo_scene.{h,cc}) -------------
TERRAIN_COLS = 30      # DEMO_TERRAIN_COLS
TERRAIN_ROWS = 15      # DEMO_TERRAIN_ROWS
TREE_COUNT = 12        # DEMO_TREE_COUNT
TERRAIN_HALF = 18      # world half-extent in X and Z (pre-scaled units)
TERRAIN_BASE_Y = 0     # ground plane Y


def cell_debug_color(cx, cy):
    """Mirror cell_debug_color() in demo_scene.cc (3 saw waves, coprime)."""
    h = (cx * 5) + (cy * 3)
    r = 64 + ((h * 37) & 0xBF)
    g = 64 + (((cy * 53) + 17) & 0xBF)
    b = 64 + (((cx * 61) + 31) & 0xBF)
    return r, g, b


def terrain_height(cx, cy):
    """Mirror terrain_height() in demo_scene.cc."""
    h = ((((cx * 7) + (cy * 11)) % 5) - 2)
    return TERRAIN_BASE_Y + h


def build_terrain():
    cols, rows = TERRAIN_COLS, TERRAIN_ROWS
    vx = cols + 1
    verts = []  # (px,py,pz, r,g,b)
    for gy in range(rows + 1):
        for gx in range(cols + 1):
            wx = -TERRAIN_HALF + ((2 * TERRAIN_HALF * gx) // cols)
            wz = -TERRAIN_HALF + ((2 * TERRAIN_HALF * gy) // rows)
            r, g, b = cell_debug_color(gx, gy)
            verts.append((wx, terrain_height(gx, gy), wz, r, g, b))
    idx = []
    for gy in range(rows):
        for gx in range(cols):
            a = (gy * vx) + gx
            b = (gy * vx) + gx + 1
            c = ((gy + 1) * vx) + gx
            d = ((gy + 1) * vx) + gx + 1
            idx += [a, b, c, b, d, c]  # CCW-from-+Y; provoking v0 = a / b
    return verts, idx


def build_trees():
    verts = []
    idx = []
    for t in range(TREE_COUNT):
        cx = -12 + ((t * 7) % 25)
        cz = -12 + ((t * 11) % 25)
        hw = 2
        ht = 5
        r = 128 + ((t * 43) & 0x7F)
        g = 128 + ((t * 29) & 0x7F)
        b = 128 + ((t * 71) & 0x7F)
        base = t * 4
        corner = ((-hw, 0), (hw, 0), (-hw, ht), (hw, ht))
        for k in range(4):
            verts.append((cx + corner[k][0], TERRAIN_BASE_Y + corner[k][1], cz,
                          r, g, b))
        a, bb, c, d = base + 0, base + 1, base + 2, base + 3
        idx += [a, c, bb, bb, c, d]  # -Z-facing order (CULL_BACK drops the back)
    return verts, idx


def fmt_vtx(v):
    # struct Vtx aggregate init: {{pos}, {uv}, {{rgba}}}. uv=0; alpha=255.
    px, py, pz, r, g, b = v
    return '{{%d, %d, %d}, {0, 0}, {{%d, %d, %d, 255}}}' % (px, py, pz, r, g, b)


def emit(name_v, name_i, verts, idx, lines):
    lines.append('static const struct Vtx %s[%d] = {' % (name_v, len(verts)))
    for v in verts:
        lines.append('    %s,' % fmt_vtx(v))
    lines.append('};')
    lines.append('static const uint16_t %s[%d] = {' % (name_i, len(idx)))
    # 12 indices per line for readability.
    for i in range(0, len(idx), 12):
        chunk = ', '.join('%d' % x for x in idx[i:i + 12])
        lines.append('    %s,' % chunk)
    lines.append('};')


def emit_header(path):
    tv, ti = build_terrain()
    rv, ri = build_trees()
    lines = []
    lines.append('// clang-format off')
    lines.append('// debug_terrain_gen.h — GENERATED by src/demo/gen_debug_terrain.py.')
    lines.append('// DO NOT EDIT. Committed FLASH-CONST placeholder terrain + tree')
    lines.append('// billboard input geometry for the D.7 demo. Baked OFFLINE so the')
    lines.append('// input geometry leaves .bss (RAM) -> fits the RP2040 RAM region')
    lines.append('// (integration-gate overflow fix). Reproduces demo_terrain_geometry')
    lines.append('// / demo_tree_geometry exactly (positions, per-cell debug colors,')
    lines.append('// indices, winding). The build does not run Python; committed data.')
    lines.append('// Regenerate: python3 src/demo/gen_debug_terrain.py src/demo/debug_terrain_gen.h')
    lines.append('#ifndef DEMO_DEBUG_TERRAIN_GEN_H')
    lines.append('#define DEMO_DEBUG_TERRAIN_GEN_H')
    lines.append('')
    lines.append('#include "rdr/types.h"')
    lines.append('')
    lines.append('// NOLINTBEGIN (generated geometry: suppress magic-number/naming lint)')
    emit('g_debug_terrain_vtx', 'g_debug_terrain_idx', tv, ti, lines)
    emit('g_debug_tree_vtx', 'g_debug_tree_idx', rv, ri, lines)
    lines.append('// NOLINTEND')
    lines.append('')
    lines.append('#endif  // DEMO_DEBUG_TERRAIN_GEN_H')
    lines.append('// clang-format on')
    lines.append('')
    text = '\n'.join(lines)
    with open(path, 'w') as fh:
        fh.write(text)
    return len(text), len(tv), len(ti), len(rv), len(ri)


def main(argv):
    out = argv[1] if len(argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), 'debug_terrain_gen.h')
    size, nv, ni, rv, ri = emit_header(out)
    sys.stderr.write(
        'wrote %s: %d bytes (terrain %dv/%di, trees %dv/%di)\n'
        % (out, size, nv, ni, rv, ri))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
