/* GENERATED by tools/asset_tool.py — do not edit by hand. */
/* Terrain per-tile triangle indices (8 tris, shared pattern) */
#ifndef TERRAIN_GRID_IDX_H
#define TERRAIN_GRID_IDX_H
#include <stdint.h>

static const uint16_t g_terrain_tile_indices[] = {
  0x0000, 0x0003, 0x0001, 0x0001, 0x0003, 0x0004, 0x0001, 0x0004,
  0x0002, 0x0002, 0x0004, 0x0005, 0x0003, 0x0006, 0x0004, 0x0004,
  0x0006, 0x0007, 0x0004, 0x0007, 0x0005, 0x0005, 0x0007, 0x0008,
};
static const unsigned g_terrain_tile_indices_len = 24;

#endif /* TERRAIN_GRID_IDX_H */
