#!/usr/bin/env python3
"""asset_tool.py — CLI for the 3D-renderer asset converter.

Wraps the pure asset_convert core with PNG loading (PIL) and Wavefront-OBJ
parsing, then emits a flat little-endian binary or a C source array placeable in
flash. Byte layout = src/rdr/types.h exactly (see asset_convert.py docstring).

Subcommands
-----------
  tex   <in.png> <out>  --fmt 565|4444  [--c-array NAME]
        PNG -> packed RGBA565/RGBA4444 texels (row-major, top-left origin).

  mesh  <in.obj> <out_vtx> <out_idx>  [--lit] [--c-array NAME]
        OBJ -> interleaved struct Vtx + uint16 index list. Pre-lit white
        (or --lit with a flat +Z normal placeholder; real normals from `vn`).
        OBJ texel UVs (`vt`, [0,1]) are scaled by the texture dimension at
        runtime; here we store s,t in S10.5 of the raw `vt` value (texel coords
        require multiplying by tex size first — done by the demo, not here).

Run without args / -h for usage.
"""

import argparse
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import asset_convert as ac  # noqa: E402

_FMT = {'565': ac.TEXFMT_RGBA565, '4444': ac.TEXFMT_RGBA4444}


def load_png_rgba(path):
    """Load a PNG to (pixels[(r,g,b,a)], w, h), row-major top-left origin."""
    from PIL import Image  # local import: only needed for PNG I/O
    img = Image.open(path).convert('RGBA')
    w, h = img.size
    return list(img.getdata()), w, h


def write_c_array_u8(path, name, data, header_comment):
    """Emit a static const uint8_t[] C source file for `data` bytes."""
    lines = [
        '/* GENERATED by tools/asset_tool.py — do not edit by hand. */',
        '/* %s */' % header_comment,
        '#include <stdint.h>',
        '',
        'const uint8_t %s[] = {' % name,
    ]
    row = []
    for i, b in enumerate(data):
        row.append('0x%02x' % b)
        if len(row) == 16 or i == len(data) - 1:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    lines.append('};')
    lines.append('const unsigned %s_len = %d;' % (name, len(data)))
    lines.append('')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))


def cmd_tex(args):
    fmt = _FMT[args.fmt]
    pixels, w, h = load_png_rgba(args.input)
    blob = ac.encode_texture(pixels, fmt)
    if args.c_array:
        write_c_array_u8(args.output, args.c_array, blob,
                         '%s %dx%d fmt=%s' % (args.input, w, h, args.fmt))
    else:
        with open(args.output, 'wb') as f:
            f.write(blob)
    print('asset_tool tex: %s %dx%d -> %s (%d bytes, fmt %s)'
          % (args.input, w, h, args.output, len(blob), args.fmt))
    return 0


def parse_obj(path):
    """Minimal Wavefront OBJ parse -> (verts, indices).

    Supports v / vt / vn / f (tri or quad, fan-triangulated). Each unique
    (v, vt, vn) tuple becomes one output vertex (deduplicated). Returns
    verts as list of (pos, uv, normal) and indices as a flat list."""
    positions = []
    texcoords = []
    normals = []
    out_verts = []
    out_idx = []
    seen = {}

    def emit_corner(spec):
        parts = (spec.split('/') + ['', ''])[:3]
        vi = int(parts[0]) - 1
        ti = int(parts[1]) - 1 if parts[1] else -1
        ni = int(parts[2]) - 1 if parts[2] else -1
        key = (vi, ti, ni)
        if key in seen:
            return seen[key]
        pos = positions[vi]
        uv = texcoords[ti] if ti >= 0 else (0.0, 0.0)
        nrm = normals[ni] if ni >= 0 else (0.0, 0.0, 1.0)
        idx = len(out_verts)
        out_verts.append((pos, uv, nrm))
        seen[key] = idx
        return idx

    with open(path) as f:
        for line in f:
            tok = line.split()
            if not tok:
                continue
            if tok[0] == 'v':
                positions.append((float(tok[1]), float(tok[2]), float(tok[3])))
            elif tok[0] == 'vt':
                texcoords.append((float(tok[1]), float(tok[2])))
            elif tok[0] == 'vn':
                normals.append((float(tok[1]), float(tok[2]), float(tok[3])))
            elif tok[0] == 'f':
                corners = [emit_corner(c) for c in tok[1:]]
                for k in range(1, len(corners) - 1):  # fan triangulate
                    out_idx += [corners[0], corners[k], corners[k + 1]]
    return out_verts, out_idx


def cmd_mesh(args):
    raw_verts, indices = parse_obj(args.input)
    verts = []
    for pos, uv, nrm in raw_verts:
        ipos = (int(round(pos[0])), int(round(pos[1])), int(round(pos[2])))
        if args.lit:
            n = (max(-128, min(127, int(round(nrm[0] * 127)))),
                 max(-128, min(127, int(round(nrm[1] * 127)))),
                 max(-128, min(127, int(round(nrm[2] * 127)))))
            verts.append((ipos, uv, (n, 255)))
        else:
            verts.append((ipos, uv, (255, 255, 255, 255)))
    vblob = ac.encode_vertices(verts, args.lit)
    iblob = ac.encode_indices(indices)
    if args.c_array:
        write_c_array_u8(args.out_vtx, args.c_array + '_vtx', vblob,
                         '%s vertices (lit=%d)' % (args.input, int(args.lit)))
        write_c_array_u8(args.out_idx, args.c_array + '_idx', iblob,
                         '%s indices' % args.input)
    else:
        with open(args.out_vtx, 'wb') as f:
            f.write(vblob)
        with open(args.out_idx, 'wb') as f:
            f.write(iblob)
    print('asset_tool mesh: %s -> %d verts (%d B), %d tris (%d B)'
          % (args.input, len(verts), len(vblob),
             len(indices) // 3, len(iblob)))
    return 0


def build_parser():
    p = argparse.ArgumentParser(description='3D renderer asset converter')
    sub = p.add_subparsers(dest='cmd')

    t = sub.add_parser('tex', help='PNG -> RGBA565/4444 texels')
    t.add_argument('input')
    t.add_argument('output')
    t.add_argument('--fmt', choices=list(_FMT.keys()), default='565')
    t.add_argument('--c-array', default=None,
                   help='emit a C source array of this name instead of binary')
    t.set_defaults(func=cmd_tex)

    m = sub.add_parser('mesh', help='OBJ -> Vtx + index list')
    m.add_argument('input')
    m.add_argument('out_vtx')
    m.add_argument('out_idx')
    m.add_argument('--lit', action='store_true',
                   help='emit normal+alpha union arm (else pre-lit white RGBA)')
    m.add_argument('--c-array', default=None)
    m.set_defaults(func=cmd_mesh)
    return p


def main(argv):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, 'func', None):
        parser.print_help()
        return 2
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
