#!/usr/bin/env python3
"""asset_tool.py — CLI for the 3D-renderer asset converter.

Wraps the pure asset_convert core with PNG loading (PIL) and Wavefront-OBJ
parsing, then emits a flat little-endian binary or a C source array placeable in
flash. Byte layout = src/rdr/types.h exactly (see asset_convert.py docstring).

Subcommands
-----------
  tex   <in.png> <out>  --fmt 565|4444  [--c-array NAME]
        PNG -> packed RGBA565/RGBA4444 texels (row-major, top-left origin).

  mesh  <in.obj> <out_vtx> <out_idx>  [--lit] [--c-array NAME]
        OBJ -> interleaved struct Vtx + uint16 index list. Pre-lit white
        (or --lit with a flat +Z normal placeholder; real normals from `vn`).
        OBJ texel UVs (`vt`, [0,1]) are scaled by the texture dimension at
        runtime; here we store s,t in S10.5 of the raw `vt` value (texel coords
        require multiplying by tex size first — done by the demo, not here).

  terrain-bake  <n64_terrain_dir> <out_dir>
        Parse the N64 terrain C source and bake all assets into out_dir:
          terrain_grid_vtx.h  — 128*9 pre-lit vertices (per-tile, pre-scaled)
          terrain_grid_idx.h  — shared 8-tri index pattern (24 uint16)
          terrain_tex_t<N>.h  — one 36x34 RGBA5551 LE tile per file, N=0..127
          terrain_detail.h    — 32x32 I8 detail texture
          terrain_tlut.h      — 256-entry RGBA5551 TLUT (panorama palette)
          terrain_panorama.h  — CI8 512x64 panorama image indices
          terrain_scenery.h   — instance table (128 entries, pre-scaled)

Run without args / -h for usage.
"""

import argparse
import hashlib
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import asset_convert as ac  # noqa: E402

_FMT = {'565': ac.TEXFMT_RGBA565, '4444': ac.TEXFMT_RGBA4444}

# Terrain source directory layout (relative to n64_terrain_dir/src/assets/)
_TERRAIN_GRID_C = 'terrain_grid.c'
_TERRAIN_TEX_C = 'terrain_tex.c'
_TERRAIN_DETAIL_C = 'terrain_detail.c'
_PANORAMA_C = 'panorama.c'
_PANORAMA_TLUT_INC = 'panorama_tlut.inc.c'
_PANORAMA_IMG_INC = 'panorama_img.inc.c'
_SCENERY_C = 'scenery_cylinders.c'
_TREE_TEX_INC = ['tree0.inc.c', 'tree1.inc.c', 'tree2.inc.c']

# Terrain tile dimensions (post-s4 gutter-padded block)
_TILE_W = 36
_TILE_H = 34
_NUM_TILES = 128
_PANORAMA_W = 512
_PANORAMA_H = 64
_PANORAMA_TLUT_ENTRIES = 256
_DETAIL_W = 32
_DETAIL_H = 32


def load_png_rgba(path):
    """Load a PNG to (pixels[(r,g,b,a)], w, h), row-major top-left origin."""
    from PIL import Image  # local import: only needed for PNG I/O
    img = Image.open(path).convert('RGBA')
    w, h = img.size
    return list(img.getdata()), w, h


def write_c_array_u8(path, name, data, header_comment):
    """Emit a static const uint8_t[] C source file for `data` bytes."""
    lines = [
        '/* GENERATED by tools/asset_tool.py — do not edit by hand. */',
        '/* %s */' % header_comment,
        '#include <stdint.h>',
        '',
        'const uint8_t %s[] = {' % name,
    ]
    row = []
    for i, b in enumerate(data):
        row.append('0x%02x' % b)
        if len(row) == 16 or i == len(data) - 1:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    lines.append('};')
    lines.append('const unsigned %s_len = %d;' % (name, len(data)))
    lines.append('')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))


def write_h_array_u8(path, guard, name, data, header_comment):
    """Emit a static const uint8_t[] C header file for `data` bytes."""
    lines = [
        '/* GENERATED by tools/asset_tool.py — do not edit by hand. */',
        '/* %s */' % header_comment,
        '#ifndef %s' % guard,
        '#define %s' % guard,
        '#include <stdint.h>',
        '',
        'static const uint8_t %s[] = {' % name,
    ]
    row = []
    for i, b in enumerate(data):
        row.append('0x%02x' % b)
        if len(row) == 16 or i == len(data) - 1:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    lines.append('};')
    lines.append('static const unsigned %s_len = %d;' % (name, len(data)))
    lines.append('')
    lines.append('#endif /* %s */' % guard)
    lines.append('')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))


def write_h_array_u16(path, guard, name, data_u16, header_comment):
    """Emit a static const uint16_t[] C header file for data_u16 (list of ints)."""
    lines = [
        '/* GENERATED by tools/asset_tool.py — do not edit by hand. */',
        '/* %s */' % header_comment,
        '#ifndef %s' % guard,
        '#define %s' % guard,
        '#include <stdint.h>',
        '',
        'static const uint16_t %s[] = {' % name,
    ]
    row = []
    for i, v in enumerate(data_u16):
        row.append('0x%04x' % (v & 0xFFFF))
        if len(row) == 8 or i == len(data_u16) - 1:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    lines.append('};')
    lines.append('static const unsigned %s_len = %d;' % (name, len(data_u16)))
    lines.append('')
    lines.append('#endif /* %s */' % guard)
    lines.append('')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))


def write_h_struct_vtx_array(path, guard, name, vtx_bytes, header_comment):
    """Emit a static const uint8_t[] for raw Vtx data (14B per vertex) as a header."""
    write_h_array_u8(path, guard, name, vtx_bytes, header_comment)


def _read_asset_src(n64_dir, filename):
    """Read an asset C source file from n64_dir/src/assets/."""
    path = os.path.join(n64_dir, 'src', 'assets', filename)
    with open(path, 'r') as f:
        return f.read()


def _read_asset_inc(n64_dir, filename):
    """Read a raw .inc.c file from n64_dir/src/assets/ as bytes."""
    path = os.path.join(n64_dir, 'src', 'assets', filename)
    with open(path, 'rb') as f:
        return f.read()


def _crc32_hex(data):
    """Return CRC32 hex string for data bytes."""
    import binascii
    return '%08x' % (binascii.crc32(data) & 0xFFFFFFFF)


def cmd_terrain_bake(args):
    n64_dir = args.n64_dir
    out_dir = args.out_dir
    os.makedirs(out_dir, exist_ok=True)

    print('terrain-bake: reading N64 source from %s' % n64_dir)

    # ---- 1. Terrain grid vertices ----
    grid_src = _read_asset_src(n64_dir, _TERRAIN_GRID_C)
    grid_verts = ac.parse_n64_terrain_grid_c(grid_src)
    print('  grid: parsed %d vertices' % len(grid_verts))
    if len(grid_verts) != 594:
        print('  WARNING: expected 594 grid entries, got %d' % len(grid_verts))

    # Bake per-tile vertex arrays (128 tiles * 9 verts = 1152 verts)
    all_tile_vtx = bytearray()
    for ty in range(16):
        for tx in range(8):
            tile_verts = ac.bake_terrain_tile_vertices(
                grid_verts, tx, ty, ac.TERRAIN_PRE_SCALE)
            for pos, uv, rgba in tile_verts:
                all_tile_vtx += ac.encode_vertex_prelit(pos, uv, rgba)

    vtx_path = os.path.join(out_dir, 'terrain_grid_vtx.h')
    write_h_struct_vtx_array(
        vtx_path,
        'TERRAIN_GRID_VTX_H',
        'g_terrain_grid_vtx',
        bytes(all_tile_vtx),
        'Terrain 128x9 pre-lit vertices (pre-scale=%.4f), 14B each' %
        ac.TERRAIN_PRE_SCALE
    )
    print('  grid vtx: %d tiles * 9 verts = %d bytes -> %s' %
          (_NUM_TILES, len(all_tile_vtx), vtx_path))
    print('    CRC32: %s' % _crc32_hex(bytes(all_tile_vtx)))

    # Shared per-tile triangle index pattern (8 tris, 24 indices)
    tile_idx = ac.bake_terrain_tile_indices()
    idx_blob = ac.encode_indices(tile_idx)
    idx_path = os.path.join(out_dir, 'terrain_grid_idx.h')
    write_h_array_u16(
        idx_path,
        'TERRAIN_GRID_IDX_H',
        'g_terrain_tile_indices',
        [struct.unpack_from('<H', idx_blob, i * 2)[0]
         for i in range(len(idx_blob) // 2)],
        'Terrain per-tile triangle indices (8 tris, shared pattern)'
    )
    print('  grid idx: %d tris, %d bytes -> %s' %
          (len(tile_idx) // 3, len(idx_blob), idx_path))

    # ---- 2. Terrain texture tiles ----
    tex_src = _read_asset_src(n64_dir, _TERRAIN_TEX_C)
    tex_values = ac.parse_n64_hex_array_c(tex_src, dtype='u16')
    expected_texels = _NUM_TILES * _TILE_W * _TILE_H
    print('  tex: parsed %d u16 values (expected %d)' %
          (len(tex_values), expected_texels))
    if len(tex_values) != expected_texels:
        print('  ERROR: terrain tex size mismatch! Expected %d, got %d' %
              (expected_texels, len(tex_values)))
        return 1

    tex_total_bytes = 0
    for t in range(_NUM_TILES):
        blob = ac.encode_terrain_tile_rgba5551_le(
            tex_values, t, _TILE_W, _TILE_H)
        tile_path = os.path.join(out_dir, 'terrain_tex_t%03d.h' % t)
        write_h_array_u8(
            tile_path,
            'TERRAIN_TEX_T%03d_H' % t,
            'g_terrain_tex_t%d' % t,
            blob,
            'Terrain tile %d/%d: %dx%d RGBA5551 LE (%d bytes)' %
            (t, _NUM_TILES, _TILE_W, _TILE_H, len(blob))
        )
        tex_total_bytes += len(blob)
    print('  tex tiles: %d tiles, %d bytes total -> terrain_tex_t*.h' %
          (_NUM_TILES, tex_total_bytes))

    # CRC of first tile for test reference
    first_tile_blob = ac.encode_terrain_tile_rgba5551_le(tex_values, 0, _TILE_W, _TILE_H)
    print('    tile 0 CRC32: %s (first texel LE: %02x %02x)' %
          (_crc32_hex(first_tile_blob), first_tile_blob[0], first_tile_blob[1]))

    # ---- 3. Detail texture (I8) ----
    detail_src = _read_asset_src(n64_dir, _TERRAIN_DETAIL_C)
    detail_values = ac.parse_n64_hex_array_c(detail_src, dtype='u8')
    expected_detail = _DETAIL_W * _DETAIL_H
    print('  detail: parsed %d bytes (expected %d)' %
          (len(detail_values), expected_detail))
    if len(detail_values) != expected_detail:
        print('  WARNING: detail size mismatch')
    detail_blob = ac.encode_i8_blob(detail_values[:expected_detail])
    detail_path = os.path.join(out_dir, 'terrain_detail.h')
    write_h_array_u8(
        detail_path,
        'TERRAIN_DETAIL_H',
        'g_terrain_detail',
        detail_blob,
        'Terrain detail noise: %dx%d I8 (%d bytes)' %
        (_DETAIL_W, _DETAIL_H, len(detail_blob))
    )
    print('  detail: %d bytes -> %s' % (len(detail_blob), detail_path))

    # ---- 4. Panorama TLUT + CI8 image ----
    pan_src = _read_asset_src(n64_dir, _PANORAMA_C)

    # Parse TLUT: 256 big-endian RGBA5551 u16 values from panorama_tlut.inc.c
    tlut_inc = _read_asset_src(n64_dir, _PANORAMA_TLUT_INC)
    tlut_values = ac.parse_n64_hex_array_c(tlut_inc, dtype='u8')
    print('  panorama TLUT: parsed %d bytes (expected %d)' %
          (len(tlut_values), _PANORAMA_TLUT_ENTRIES * 2))

    # Decode TLUT entries (big-endian RGBA5551) then re-encode as LE
    tlut_rgba = ac.decode_tlut_from_n64_blob(
        bytes(tlut_values), _PANORAMA_TLUT_ENTRIES)
    tlut_blob = ac.encode_tlut_rgba5551(tlut_rgba)
    tlut_path = os.path.join(out_dir, 'terrain_tlut.h')
    write_h_array_u8(
        tlut_path,
        'TERRAIN_TLUT_H',
        'g_terrain_panorama_tlut',
        tlut_blob,
        'Panorama TLUT: %d RGBA5551 LE entries (%d bytes)' %
        (_PANORAMA_TLUT_ENTRIES, len(tlut_blob))
    )
    print('  TLUT: %d entries, %d bytes -> %s' %
          (_PANORAMA_TLUT_ENTRIES, len(tlut_blob), tlut_path))

    # Parse panorama CI8 image bytes from panorama_img.inc.c
    img_inc = _read_asset_src(n64_dir, _PANORAMA_IMG_INC)
    img_values = ac.parse_n64_hex_array_c(img_inc, dtype='u8')
    expected_pan = _PANORAMA_W * _PANORAMA_H
    print('  panorama img: parsed %d bytes (expected %d)' %
          (len(img_values), expected_pan))
    if len(img_values) != expected_pan:
        print('  WARNING: panorama size mismatch, got %d expected %d'
              % (len(img_values), expected_pan))
    pan_blob = ac.encode_ci8_blob(img_values[:expected_pan])
    pan_path = os.path.join(out_dir, 'terrain_panorama.h')
    write_h_array_u8(
        pan_path,
        'TERRAIN_PANORAMA_H',
        'g_terrain_panorama',
        pan_blob,
        'Panorama CI8: %dx%d (%d bytes), uses g_terrain_panorama_tlut' %
        (_PANORAMA_W, _PANORAMA_H, len(pan_blob))
    )
    print('  panorama CI8: %d bytes -> %s' % (len(pan_blob), pan_path))

    # ---- 5. Tree textures (RGBA5551 LE) ----
    for t_idx in range(3):
        inc_src = _read_asset_src(n64_dir, _TREE_TEX_INC[t_idx])
        tree_values = ac.parse_n64_hex_array_c(inc_src, dtype='u8')
        # 32*64*2 = 4096 bytes big-endian RGBA5551
        expected_tree = 32 * 64 * 2
        print('  tree%d: parsed %d bytes (expected %d)' %
              (t_idx, len(tree_values), expected_tree))
        if len(tree_values) != expected_tree:
            print('  WARNING: tree%d size mismatch' % t_idx)
        tree_blob = ac.n64_rgba5551_be_to_le_blob(
            bytes(tree_values[:expected_tree]))
        tree_path = os.path.join(out_dir, 'terrain_tree%d.h' % t_idx)
        write_h_array_u8(
            tree_path,
            'TERRAIN_TREE%d_H' % t_idx,
            'g_terrain_tree%d' % t_idx,
            tree_blob,
            'Tree%d billboard: 32x64 RGBA5551 LE (%d bytes)' %
            (t_idx, len(tree_blob))
        )
        print('  tree%d: %d bytes -> %s' % (t_idx, len(tree_blob), tree_path))

    # ---- 6. Scenery instance table ----
    scen_src = _read_asset_src(n64_dir, _SCENERY_C)
    scen_entries = ac.parse_n64_scenery_cylinders_c(scen_src)
    # Filter out dead entries (sprite_id < 0)
    live_entries = [e for e in scen_entries if e['sprite_id'] >= 0]
    print('  scenery: parsed %d total, %d live' %
          (len(scen_entries), len(live_entries)))

    # Emit as a C header with a simple flat struct layout.
    # Each entry: int16 cx, int16 y, int16 cz, int8 sprite_id,
    #             uint8 visibility, int16 radius, int16 height = 10 bytes.
    # Pre-scale cx, y, cz, radius, height by TERRAIN_PRE_SCALE.
    scen_lines = [
        '/* GENERATED by tools/asset_tool.py — do not edit by hand. */',
        '/* Terrain scenery instance table (%d live entries, pre-scale=%.4f) */'
        % (len(live_entries), ac.TERRAIN_PRE_SCALE),
        '#ifndef TERRAIN_SCENERY_H',
        '#define TERRAIN_SCENERY_H',
        '#include <stdint.h>',
        '',
        'struct TerrainSceneryEntry {',
        '  int16_t cx, y, cz;',
        '  int8_t sprite_id;',
        '  uint8_t visibility;',
        '  int16_t radius, height;',
        '};',
        '',
        'static const struct TerrainSceneryEntry g_terrain_scenery[%d] = {'
        % len(live_entries),
    ]
    for e in live_entries:
        cx = ac.round_half_away(e['cx'] * ac.TERRAIN_PRE_SCALE)
        ey = ac.round_half_away(e['y'] * ac.TERRAIN_PRE_SCALE)
        cz = ac.round_half_away(e['cz'] * ac.TERRAIN_PRE_SCALE)
        r = ac.round_half_away(e['radius'] * ac.TERRAIN_PRE_SCALE)
        h = ac.round_half_away(e['height'] * ac.TERRAIN_PRE_SCALE)
        scen_lines.append(
            '  { %d, %d, %d, %d, %d, %d, %d },'
            % (cx, ey, cz, e['sprite_id'], e['visibility'], r, h)
        )
    scen_lines.append('};')
    scen_lines.append('static const unsigned g_terrain_scenery_count = %d;'
                      % len(live_entries))
    scen_lines.append('')
    scen_lines.append('#endif /* TERRAIN_SCENERY_H */')
    scen_lines.append('')
    scen_path = os.path.join(out_dir, 'terrain_scenery.h')
    with open(scen_path, 'w') as f:
        f.write('\n'.join(scen_lines))
    print('  scenery: %d entries -> %s' % (len(live_entries), scen_path))

    print('terrain-bake: DONE. Output in %s' % out_dir)
    return 0


def cmd_tex(args):
    fmt = _FMT[args.fmt]
    pixels, w, h = load_png_rgba(args.input)
    blob = ac.encode_texture(pixels, fmt)
    if args.c_array:
        write_c_array_u8(args.output, args.c_array, blob,
                         '%s %dx%d fmt=%s' % (args.input, w, h, args.fmt))
    else:
        with open(args.output, 'wb') as f:
            f.write(blob)
    print('asset_tool tex: %s %dx%d -> %s (%d bytes, fmt %s)'
          % (args.input, w, h, args.output, len(blob), args.fmt))
    return 0


def parse_obj(path):
    """Minimal Wavefront OBJ parse -> (verts, indices).

    Supports v / vt / vn / f (tri or quad, fan-triangulated). Each unique
    (v, vt, vn) tuple becomes one output vertex (deduplicated). Returns
    verts as list of (pos, uv, normal) and indices as a flat list."""
    positions = []
    texcoords = []
    normals = []
    out_verts = []
    out_idx = []
    seen = {}

    def emit_corner(spec):
        parts = (spec.split('/') + ['', ''])[:3]
        vi = int(parts[0]) - 1
        ti = int(parts[1]) - 1 if parts[1] else -1
        ni = int(parts[2]) - 1 if parts[2] else -1
        key = (vi, ti, ni)
        if key in seen:
            return seen[key]
        pos = positions[vi]
        uv = texcoords[ti] if ti >= 0 else (0.0, 0.0)
        nrm = normals[ni] if ni >= 0 else (0.0, 0.0, 1.0)
        idx = len(out_verts)
        out_verts.append((pos, uv, nrm))
        seen[key] = idx
        return idx

    with open(path) as f:
        for line in f:
            tok = line.split()
            if not tok:
                continue
            if tok[0] == 'v':
                positions.append((float(tok[1]), float(tok[2]), float(tok[3])))
            elif tok[0] == 'vt':
                texcoords.append((float(tok[1]), float(tok[2])))
            elif tok[0] == 'vn':
                normals.append((float(tok[1]), float(tok[2]), float(tok[3])))
            elif tok[0] == 'f':
                corners = [emit_corner(c) for c in tok[1:]]
                for k in range(1, len(corners) - 1):  # fan triangulate
                    out_idx += [corners[0], corners[k], corners[k + 1]]
    return out_verts, out_idx


def cmd_mesh(args):
    raw_verts, indices = parse_obj(args.input)
    verts = []
    for pos, uv, nrm in raw_verts:
        ipos = (int(round(pos[0])), int(round(pos[1])), int(round(pos[2])))
        if args.lit:
            n = (max(-128, min(127, int(round(nrm[0] * 127)))),
                 max(-128, min(127, int(round(nrm[1] * 127)))),
                 max(-128, min(127, int(round(nrm[2] * 127)))))
            verts.append((ipos, uv, (n, 255)))
        else:
            verts.append((ipos, uv, (255, 255, 255, 255)))
    vblob = ac.encode_vertices(verts, args.lit)
    iblob = ac.encode_indices(indices)
    if args.c_array:
        write_c_array_u8(args.out_vtx, args.c_array + '_vtx', vblob,
                         '%s vertices (lit=%d)' % (args.input, int(args.lit)))
        write_c_array_u8(args.out_idx, args.c_array + '_idx', iblob,
                         '%s indices' % args.input)
    else:
        with open(args.out_vtx, 'wb') as f:
            f.write(vblob)
        with open(args.out_idx, 'wb') as f:
            f.write(iblob)
    print('asset_tool mesh: %s -> %d verts (%d B), %d tris (%d B)'
          % (args.input, len(verts), len(vblob),
             len(indices) // 3, len(iblob)))
    return 0


def build_parser():
    p = argparse.ArgumentParser(description='3D renderer asset converter')
    sub = p.add_subparsers(dest='cmd')

    t = sub.add_parser('tex', help='PNG -> RGBA565/4444 texels')
    t.add_argument('input')
    t.add_argument('output')
    t.add_argument('--fmt', choices=list(_FMT.keys()), default='565')
    t.add_argument('--c-array', default=None,
                   help='emit a C source array of this name instead of binary')
    t.set_defaults(func=cmd_tex)

    m = sub.add_parser('mesh', help='OBJ -> Vtx + index list')
    m.add_argument('input')
    m.add_argument('out_vtx')
    m.add_argument('out_idx')
    m.add_argument('--lit', action='store_true',
                   help='emit normal+alpha union arm (else pre-lit white RGBA)')
    m.add_argument('--c-array', default=None)
    m.set_defaults(func=cmd_mesh)

    tb = sub.add_parser('terrain-bake',
                        help='Bake N64 terrain assets to renderer headers')
    tb.add_argument('n64_dir', help='Path to N64 terrain project root')
    tb.add_argument('out_dir', help='Output directory for generated headers')
    tb.set_defaults(func=cmd_terrain_bake)

    return p


def main(argv):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, 'func', None):
        parser.print_help()
        return 2
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
