#!/usr/bin/env python3
"""gen_assets.py — PNG -> RGB565 + 1-bpp mask C source generator.

Usage:
    gen_assets.py <assets_dir> <out_h> <out_cc>

For every *.png in assets_dir, emits:
  - out_h : SpriteId enum + extern const Sprite declarations + sprite_get()
  - out_cc: pixel arrays, mask arrays, Sprite table, sprite_get() definition

Sprite encoding:
  color  : uint16_t RGB565 (R5 G6 B5, red in high bits), row-major.
  mask   : packed 1-bpp, row-major, bit index = y*w + x,
           byte = mask[idx>>3], bit = 0x80>>(idx&7), set=opaque.
  Alpha threshold: strict 0/255 (PNGs are already strict).

File naming → SpriteId enum:
  pico8_font.png → SPRITE_FONT  (the font atlas; always emitted last)
  <name>.png     → SPRITE_<NAME>  (uppercased; non-alphanumerics become '_')

Drop any *.png into assets_dir and it becomes a SPRITE_* id automatically — no
game-specific naming rules. The build re-runs this generator when assets change.
"""

import os
import sys
import re
from PIL import Image

# ---- ordering ----------------------------------------------------------------

# Deterministic enum order: all sprites alphabetically by stem, with the font
# atlas (pico8_font) emitted last. Order only affects enum numbering.


def sort_key(stem):
    """Return a sort key for a sprite stem (filename without .png)."""
    if stem == 'pico8_font':
        return (1, stem)  # font last
    return (0, stem)      # everything else, alphabetical


def stem_to_enum(stem):
    """Convert a filename stem to a SPRITE_XXX enum name."""
    if stem == 'pico8_font':
        return 'SPRITE_FONT'
    return 'SPRITE_' + re.sub(r'[^0-9A-Za-z]+', '_', stem).upper()


def encode_png(path):
    """Returns (pixels_rgb565: list[int], mask_bytes: list[int], w, h)."""
    img = Image.open(path).convert('RGBA')
    w, h = img.size
    pixels = list(img.getdata())

    rgb565 = []
    for r, g, b, _a in pixels:
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        rgb565.append(v)

    # pack 1-bpp mask, MSB-first
    total = w * h
    nbytes = (total + 7) // 8
    mask = [0] * nbytes
    for idx, (_r, _g, _b, a) in enumerate(pixels):
        if a > 0:
            mask[idx >> 3] |= 0x80 >> (idx & 7)

    return rgb565, mask, w, h


def c_array_u16(name, values):
    """Emit a static const uint16_t array."""
    lines = ['static const uint16_t %s[] = {' % name]
    row = []
    for i, v in enumerate(values):
        row.append('0x%04x' % v)
        if len(row) == 12 or i == len(values) - 1:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    lines.append('};')
    return '\n'.join(lines)


def c_array_u8(name, values):
    """Emit a static const uint8_t array."""
    lines = ['static const uint8_t %s[] = {' % name]
    row = []
    for i, v in enumerate(values):
        row.append('0x%02x' % v)
        if len(row) == 16 or i == len(values) - 1:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    lines.append('};')
    return '\n'.join(lines)


# ---- main --------------------------------------------------------------------

def main():
    if len(sys.argv) != 4:
        print('Usage: gen_assets.py <assets_dir> <out_h> <out_cc>', file=sys.stderr)
        sys.exit(1)

    assets_dir, out_h, out_cc = sys.argv[1], sys.argv[2], sys.argv[3]

    pngs = sorted(
        [f for f in os.listdir(assets_dir) if f.endswith('.png')],
        key=lambda f: sort_key(os.path.splitext(f)[0])
    )

    sprites = []  # list of (stem, enum_name, rgb565, mask, w, h)
    for fname in pngs:
        stem = os.path.splitext(fname)[0]
        enum_name = stem_to_enum(stem)
        path = os.path.join(assets_dir, fname)
        rgb565, mask, w, h = encode_png(path)
        sprites.append((stem, enum_name, rgb565, mask, w, h))

    # ---- emit header ---------------------------------------------------------
    guard = 'GFX_ASSETS_GEN_H'
    h_lines = [
        '/* GENERATED by tools/gen_assets.py — do not edit by hand. */',
        '#ifndef %s' % guard,
        '#define %s' % guard,
        '',
        '#include <stdint.h>',
        '#include "gfx/sprite.h"',
        '',
        '/* Sprite identifier enum. */',
        'typedef enum {',
    ]
    for i, (stem, enum_name, _rgb, _mask, _w, _h) in enumerate(sprites):
        comma = ',' if i < len(sprites) - 1 else ''
        h_lines.append('  %s = %d%s' % (enum_name, i, comma))
    h_lines += [
        '  , SPRITE_ID_COUNT = %d' % len(sprites),
        '} SpriteId;',
        '',
        '/* Return a pointer to the sprite for the given id, or NULL if out of range. */',
        'const struct Sprite* sprite_get(SpriteId id);',
        '',
        '#endif /* %s */' % guard,
        '',
    ]

    os.makedirs(os.path.dirname(out_h), exist_ok=True)
    with open(out_h, 'w') as f:
        f.write('\n'.join(h_lines))

    # ---- emit source ---------------------------------------------------------
    cc_lines = [
        '/* GENERATED by tools/gen_assets.py — do not edit by hand. */',
        '#include "gfx/assets_gen.h"',
        '',
    ]

    sprite_var_names = []
    for stem, enum_name, rgb565, mask, w, h in sprites:
        var_base = stem.lower().replace('-', '_')
        px_var = 'k_%s_px' % var_base
        mask_var = 'k_%s_mask' % var_base
        sprite_var = 'k_%s_sprite' % var_base
        sprite_var_names.append(sprite_var)

        cc_lines.append('/* %s — %dx%d */' % (stem, w, h))
        cc_lines.append(c_array_u16(px_var, rgb565))
        cc_lines.append(c_array_u8(mask_var, mask))
        cc_lines.append(
            'static const struct Sprite %s = { %s, %s, %d, %d };'
            % (sprite_var, px_var, mask_var, w, h)
        )
        cc_lines.append('')

    # table
    cc_lines.append('static const struct Sprite* const k_sprite_table[SPRITE_ID_COUNT] = {')
    for var in sprite_var_names:
        cc_lines.append('  &%s,' % var)
    cc_lines.append('};')
    cc_lines.append('')
    cc_lines += [
        'const struct Sprite* sprite_get(SpriteId id) {',
        '  if ((int)id < 0 || (int)id >= (int)SPRITE_ID_COUNT) return (const struct Sprite*)0;',
        '  return k_sprite_table[id];',
        '}',
        '',
    ]

    with open(out_cc, 'w') as f:
        f.write('\n'.join(cc_lines))

    image_count = sum(1 for s in sprites if s[1] != 'SPRITE_FONT')
    print('gen_assets: emitted %d sprites (%d image + 1 font) -> %s, %s'
          % (len(sprites), image_count, out_h, out_cc))


if __name__ == '__main__':
    main()
