/* GENERATED by tools/gen_assets.py — do not edit by hand. */
#ifndef GFX_ASSETS_GEN_H
#define GFX_ASSETS_GEN_H

#include <stdint.h>
#include "gfx/sprite.h"

/* Sprite identifier enum. */
typedef enum {
  SPRITE_FONT = 0
  , SPRITE_ID_COUNT = 1
} SpriteId;

/* Return a pointer to the sprite for the given id, or NULL if out of range. */
const struct Sprite* sprite_get(SpriteId id);

#endif /* GFX_ASSETS_GEN_H */
