/* platform_pico.cc — bare-metal PicoSystem HAL (RP2040 / ST7789)
 *
 * Implements platform.h for the Pimoroni PicoSystem.
 *
 * Pins (picosystem.hpp lines 37-41):
 *   CS=5  SCK=6  MOSI=7  LCD_RESET=4  VSYNC/TE=8  DC=9  BACKLIGHT=12
 *   UP=23 DOWN=20 LEFT=22 RIGHT=21 A=18 B=19 X=17 Y=16
 *
 * ST7789 init: verbatim from picosystem/libraries/hardware.cpp lines 357-381,
 *   with COLMOD=0x55 (RGB565) instead of 0x03 (12bpp RGB444).
 *
 * PIO: screen.pio — 16bpp, MSB-first, SCK sideset.
 * DMA: halfword (16-bit) transfers, SCREEN_PIXELS count, TE-gated.
 * Seed: pico/rand.h get_rand_32() (ROSC + time entropy).
 * Log: USB-CDC printf (pico_enable_stdio_usb set in executable's CMakeLists).
 */

#include <stdarg.h>
#include <stdio.h>

#include "gfx/framebuffer.h"
#include "hardware/adc.h"
#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/gpio.h"
#include "hardware/irq.h"
#include "hardware/pio.h"
#include "hardware/pwm.h"
#include "hardware/spi.h"
#include "hardware/vreg.h"
#include "pico/rand.h"
#include "pico/stdlib.h"
#include "pico/time.h"
#include "platform/display.h"
#include "platform/platform.h"
#include "platform/scanrace.h"
#include "screen.pio.h" /* generated by pico_generate_pio_header */

/* ---- Pin assignments (picosystem.hpp lines 37-41) ------------------------ */
enum {
  PIN_LCD_RESET = 4,
  PIN_CS = 5,
  PIN_SCK = 6,
  PIN_MOSI = 7,
  PIN_VSYNC = 8, /* TE / tear-effect input */
  PIN_DC = 9,
  PIN_AUDIO = 11, /* PWM beeper (picosystem.hpp line 40: AUDIO = 11) */
  PIN_BACKLIGHT = 12,

  PIN_UP = 23,
  PIN_DOWN = 20,
  PIN_LEFT = 22,
  PIN_RIGHT = 21,
  PIN_A = 18,
  PIN_B = 19,
  PIN_X = 17,
  PIN_Y = 16,
};

/* ---- Module state -------------------------------------------------------- */
static PIO s_pio = pio0;
static uint s_sm = 0;
static int s_dma_chan = -1;

static uint32_t s_held_prev = 0;

/* Scanline-race guard: present DMA chases the renderer's committed watermark
 * and never streams past it (stall-rather-than-tear). The renderer/scheduler
 * advances the watermark via plat_present_watermark() as tile-row bands finish;
 * a watermark of 0 means "no banding info" → plat_present streams the whole
 * frame after TE (the simple, always-correct fallback). */
static volatile uint16_t s_committed_rows = 0;

/* Audio: stop_ms == 0 means silent; >0 means tone active until that timestamp.
 */
static uint32_t s_audio_stop_ms = 0;
/* PWM wrap used for audio frequency calculation (hardware.cpp line 33) */
static const uint32_t AUDIO_PWM_WRAP = 5000U;

/* ---- ST7789 command enum (hardware.cpp lines 347-355) -------------------- */
enum St7789Cmd {
  SWRESET = 0x01,
  TEON = 0x35,
  MADCTL = 0x36,
  COLMOD = 0x3A,
  GCTRL = 0xB7,
  VCOMS = 0xBB,
  LCMCTRL = 0xC0,
  VDVVRHEN = 0xC2,
  VRHS = 0xC3,
  VDVS = 0xC4,
  FRCTRL2 = 0xC6,
  PWRCTRL1 = 0xD0,
  FRMCTR2 = 0xB2,
  GMCTRP1 = 0xE0,
  GMCTRN1 = 0xE1,
  INVON = 0x21,
  SLPOUT = 0x11,
  DISPON = 0x29,
  GAMSET = 0x26,
  RAMWR = 0x2C,
  CASET = 0x2A,
  RASET = 0x2B,
};

/* ---- Helpers ------------------------------------------------------------- */
static void screen_cmd(uint8_t cmd, size_t len, const uint8_t *data) {
  gpio_put(PIN_CS, 0);
  gpio_put(PIN_DC, 0);
  spi_write_blocking(spi0, &cmd, 1);
  if (data && len > 0) {
    gpio_put(PIN_DC, 1);
    spi_write_blocking(spi0, data, len);
  }
  gpio_put(PIN_CS, 1);
}

static void screen_cmd0(uint8_t cmd) { screen_cmd(cmd, 0, 0); }

/* ---- plat_init ----------------------------------------------------------- */
void plat_init(void) {
  /* Overclock: vreg 1.20V then 250 MHz (hardware.cpp lines 303-306) */
  vreg_set_voltage(VREG_VOLTAGE_1_20);
  sleep_ms(10);
  set_sys_clock_khz(250000, true);

  /* Backlight PWM — off during init (hardware.cpp lines 293-298) */
  {
    pwm_config cfg = pwm_get_default_config();
    pwm_set_wrap(pwm_gpio_to_slice_num(PIN_BACKLIGHT), 65535);
    pwm_init(pwm_gpio_to_slice_num(PIN_BACKLIGHT), &cfg, true);
    gpio_set_function(PIN_BACKLIGHT, GPIO_FUNC_PWM);
    pwm_set_gpio_level(PIN_BACKLIGHT, 0);
  }

  /* Button inputs, pull-ups (hardware.cpp init_inputs, lines 44-53) */
  {
    static const uint8_t btns[] = {PIN_UP, PIN_DOWN, PIN_LEFT, PIN_RIGHT,
                                   PIN_A,  PIN_B,    PIN_X,    PIN_Y};
    for (size_t i = 0; i < sizeof btns / sizeof *btns; ++i) {
      gpio_set_function(btns[i], GPIO_FUNC_SIO);
      gpio_set_dir(btns[i], GPIO_IN);
      gpio_pull_up(btns[i]);
    }
  }

  /* SPI0 for ST7789 init at 8 MHz (hardware.cpp line 330) */
  spi_init(spi0, 8000000);

  /* Reset cycle (hardware.cpp lines 332-335) */
  gpio_set_function(PIN_LCD_RESET, GPIO_FUNC_SIO);
  gpio_set_dir(PIN_LCD_RESET, GPIO_OUT);
  gpio_put(PIN_LCD_RESET, 0);
  sleep_ms(100);
  gpio_put(PIN_LCD_RESET, 1);

  /* DC and CS as SIO outputs (hardware.cpp lines 337-339) */
  gpio_set_function(PIN_DC, GPIO_FUNC_SIO);
  gpio_set_dir(PIN_DC, GPIO_OUT);
  gpio_set_function(PIN_CS, GPIO_FUNC_SIO);
  gpio_set_dir(PIN_CS, GPIO_OUT);

  gpio_set_function(PIN_SCK, GPIO_FUNC_SPI);
  gpio_set_function(PIN_MOSI, GPIO_FUNC_SPI);

  gpio_put(PIN_CS, 1);

  /* ST7789 init sequence — verbatim from hardware.cpp lines 357-381
   * ONE change: COLMOD = 0x55 (RGB565) instead of 0x03 (12bpp RGB444)
   * per design spec (COLMOD §9.1.32, ST7789 datasheet p224). */
  {
    screen_cmd0(SWRESET);
    sleep_ms(5);

    /* MADCTL = 0x04: RGB order, MY=0 → window 0x00..0xEF, no offset
     * (hardware.cpp line 359; MADCTL §9.1.28, datasheet p215) */
    screen_cmd(MADCTL, 1, (const uint8_t *)"\x04");

    /* TEON = 0x00: tear-effect on (hardware.cpp line 360;
     * TEON §9.1.27, datasheet p213) */
    screen_cmd(TEON, 1, (const uint8_t *)"\x00");

    /* FRMCTR2 porch settings (hardware.cpp line 361) */
    screen_cmd(FRMCTR2, 5, (const uint8_t *)"\x0C\x0C\x00\x33\x33");

    /* COLMOD = 0x55: 16-bit RGB565 (spec change vs hardware.cpp 0x03) */
    screen_cmd(COLMOD, 1, (const uint8_t *)"\x55");

    /* GAMSET = 0x01: gamma curve 1 (hardware.cpp line 363) */
    screen_cmd(GAMSET, 1, (const uint8_t *)"\x01");

    /* Power / voltage settings (hardware.cpp lines 365-372) */
    screen_cmd(GCTRL, 1, (const uint8_t *)"\x14");
    screen_cmd(VCOMS, 1, (const uint8_t *)"\x25");
    screen_cmd(LCMCTRL, 1, (const uint8_t *)"\x2C");
    screen_cmd(VDVVRHEN, 1, (const uint8_t *)"\x01");
    screen_cmd(VRHS, 1, (const uint8_t *)"\x12");
    screen_cmd(VDVS, 1, (const uint8_t *)"\x20");
    screen_cmd(PWRCTRL1, 2, (const uint8_t *)"\xA4\xA1");
    screen_cmd(FRCTRL2, 1, (const uint8_t *)"\x1E");

    /* Gamma tables — verbatim (hardware.cpp lines 373-374) */
    screen_cmd(
        GMCTRP1, 14,
        (const uint8_t
             *)"\xD0\x04\x0D\x11\x13\x2B\x3F\x54\x4C\x18\x0D\x0B\x1F\x23");
    screen_cmd(
        GMCTRN1, 14,
        (const uint8_t
             *)"\xD0\x04\x0C\x11\x13\x2C\x3F\x44\x51\x2F\x1F\x1F\x20\x23");

    /* INVON required for correct color rendering (hardware.cpp line 375) */
    screen_cmd0(INVON);
    sleep_ms(115);

    screen_cmd0(SLPOUT);
    screen_cmd0(DISPON);

    /* CASET/RASET: 0x00..0xEF (240 columns/rows, no offset)
     * (hardware.cpp lines 379-380; MADCTL=0x04 → MY=0 → no RASET offset) */
    screen_cmd(CASET, 4, (const uint8_t *)"\x00\x00\x00\xEF");
    screen_cmd(RASET, 4, (const uint8_t *)"\x00\x00\x00\xEF");

    /* RAMWR — panel now expects pixel data (hardware.cpp line 381) */
    screen_cmd0(RAMWR);
  }

  /* Latch CS/DC into data mode for PIO streaming (hardware.cpp lines 385-386)
   */
  gpio_put(PIN_CS, 0);
  gpio_put(PIN_DC, 1);

  /* Switch SCK/MOSI from SPI0 to PIO (hardware.cpp lines 217-218) */
  gpio_set_function(PIN_SCK, GPIO_FUNC_NULL);
  gpio_set_function(PIN_MOSI, GPIO_FUNC_NULL);

  /* TE/VSYNC input (hardware.cpp lines 396-398) */
  gpio_init(PIN_VSYNC);
  gpio_set_dir(PIN_VSYNC, GPIO_IN);

  /* PIO screen program (screen.pio; see also hardware.cpp lines 400-401) */
  {
    const uint offset = pio_add_program(s_pio, &screen_program);
    screen_program_init(s_pio, s_sm, offset, PIN_MOSI, PIN_SCK);
  }

  /* DMA channel — 16-bit halfword transfers to PIO TX FIFO.
   * No bswap: PIO shifts left (MSB-first) so byte order is handled in PIO.
   * (DMA §2.5, hardware_dma/include/hardware/dma.h) */
  {
    s_dma_chan = dma_claim_unused_channel(true);
    dma_channel_config cfg = dma_channel_get_default_config((uint)s_dma_chan);
    channel_config_set_transfer_data_size(&cfg, DMA_SIZE_16);
    channel_config_set_bswap(&cfg, false);
    channel_config_set_dreq(&cfg, pio_get_dreq(s_pio, s_sm, true));
    /* Write address = PIO TX FIFO; fixed (no write-increment) */
    dma_channel_configure((uint)s_dma_chan, &cfg,
                          &s_pio->txf[s_sm], /* write address */
                          NULL,              /* read address set per transfer */
                          SCREEN_PIXELS,     /* transfer count (16-bit words) */
                          false              /* don't trigger yet */
    );
  }

  /* Audio PWM on GPIO11 (PIN_AUDIO).
   * Verbatim setup from picosystem/libraries/hardware.cpp lines 418-423:
   *   int audio_pwm_slice_number = pwm_gpio_to_slice_num(AUDIO);
   *   pwm_config audio_pwm_cfg = pwm_get_default_config();
   *   pwm_init(audio_pwm_slice_number, &audio_pwm_cfg, true);
   *   gpio_set_function(AUDIO, GPIO_FUNC_PWM);
   *   pwm_set_gpio_level(AUDIO, 0);
   */
  {
    const uint audio_slice = pwm_gpio_to_slice_num(PIN_AUDIO);
    pwm_config audio_cfg = pwm_get_default_config();
    pwm_init(audio_slice, &audio_cfg, true);
    gpio_set_function(PIN_AUDIO, GPIO_FUNC_PWM);
    pwm_set_gpio_level(PIN_AUDIO, 0);
  }

  /* Backlight on at 50% after init complete */
  pwm_set_gpio_level(PIN_BACKLIGHT, 32767);

  /* USB-CDC stdio init (pico_enable_stdio_usb set in executable's CMakeLists)
   */
  stdio_init_all();
}

/* ---- plat_present_watermark ---------------------------------------------- */
/* Scheduler publishes committed scanline rows as bands resolve; the present DMA
 * chases this and never streams past it (display.h). volatile because it is
 * written from a producer context and polled by the DMA-chase loop. */
void plat_present_watermark(uint16_t committed_rows) {
  if (committed_rows > SCREEN_H) {
    committed_rows = SCREEN_H;
  }
  if (committed_rows > s_committed_rows) {
    s_committed_rows = committed_rows; /* monotonic within a frame */
  }
}

/* ---- plat_present -------------------------------------------------------- */
void plat_present(const struct Framebuffer *fb) {
  /* Gate on TE (VSYNC) rising edge to avoid tearing
   * (hardware.cpp _wait_vsync() lines 105-108), but BOUND the wait: if the
   * display's TE line stalls, give up after ~100 ms and present anyway. A torn
   * frame beats a permanent core0 wedge in this busy-wait (the only unbounded
   * loop in the present path). time_us_64 is wrap-safe (T5 probe checklist). */
  uint64_t const te_deadline = time_us_64() + 100000U; /* 100 ms */
  while (gpio_get(PIN_VSYNC) && time_us_64() < te_deadline) { /* TE to fall */
  }
  while (!gpio_get(PIN_VSYNC) && time_us_64() < te_deadline) { /* TE rising */
  }

  /* Scanline-race chase: stream the framebuffer in watermark-bounded bands so
   * the DMA never streams a row the renderer has not committed. If no watermark
   * was published this frame (s_committed_rows == 0), treat the whole frame as
   * committed — the simple, always-correct full-frame path (PIO shifts
   * MSB-first so no CPU byteswap; design spec / hardware.cpp lines 175-179). */
  struct ScanRace race;
  scanrace_init(&race, SCREEN_H);
  if (s_committed_rows == 0) {
    scanrace_set_watermark(&race, SCREEN_H);
  }

  while (!scanrace_done(&race)) {
    /* Pull the latest committed watermark (producer advances it concurrently).
     */
    scanrace_set_watermark(&race, s_committed_rows);

    const uint16_t runway = scanrace_runway(&race);
    if (runway == 0) {
      /* Caught up to the watermark but frame not done → stall (no tear). */
      tight_loop_contents();
      continue;
    }

    /* Stream `runway` scanlines: 16-bit words from the right row offset. */
    const uint32_t first_row = race.dma_rows_sent;
    const uint32_t count = (uint32_t)runway * (uint32_t)SCREEN_W;
    dma_channel_set_read_addr((uint)s_dma_chan, fb->px + (first_row * SCREEN_W),
                              false);
    dma_channel_set_trans_count((uint)s_dma_chan, count, true /* trigger */);
    dma_channel_wait_for_finish_blocking((uint)s_dma_chan);

    scanrace_advance_dma(&race, runway);
  }

  /* Reset the watermark for the next frame. */
  s_committed_rows = 0;
}

/* ---- plat_poll_input ----------------------------------------------------- */
bool plat_poll_input(struct Input *out) {
  /* Buttons are active-low with pull-ups (hardware.cpp init_inputs,
   * picosystem.hpp button() function line 71: !(_io & (1U << b))) */
  const uint32_t gpio_state = gpio_get_all();

  uint32_t held = 0;
  if (!(gpio_state & (1U << PIN_UP))) {
    held |= BTN_UP;
  }
  if (!(gpio_state & (1U << PIN_DOWN))) {
    held |= BTN_DOWN;
  }
  if (!(gpio_state & (1U << PIN_LEFT))) {
    held |= BTN_LEFT;
  }
  if (!(gpio_state & (1U << PIN_RIGHT))) {
    held |= BTN_RIGHT;
  }
  if (!(gpio_state & (1U << PIN_A))) {
    held |= BTN_A;
  }
  if (!(gpio_state & (1U << PIN_B))) {
    held |= BTN_B;
  }
  if (!(gpio_state & (1U << PIN_X))) {
    held |= BTN_X;
  }
  if (!(gpio_state & (1U << PIN_Y))) {
    held |= BTN_Y;
  }

  out->held = held;
  out->pressed = held & ~s_held_prev; /* rising-edge detection */
  s_held_prev = held;

  /* Non-blocking audio stop: silence PWM when the tone duration expires. */
  if (s_audio_stop_ms != 0 &&
      to_ms_since_boot(get_absolute_time()) >= s_audio_stop_ms) {
    pwm_set_gpio_level(PIN_AUDIO, 0);
    s_audio_stop_ms = 0;
  }

  return true; /* pico never requests shutdown */
}

/* ---- plat_millis --------------------------------------------------------- */
uint32_t plat_millis(void) {
  /* hardware.cpp time() lines 85-88 */
  return to_ms_since_boot(get_absolute_time());
}

/* ---- plat_seed ----------------------------------------------------------- */
uint32_t plat_seed(void) {
  /* pico/rand.h get_rand_32(): uses ROSC + time + bus-perf-counter entropy
   * (pico_rand/include/pico/rand.h line 211) */
  return get_rand_32();
}

/* ---- plat_log ------------------------------------------------------------ */
void plat_log(const char *fmt, ...) {
  va_list ap;
  va_start(ap, fmt);
  vprintf(fmt, ap); /* routes to USB-CDC when pico_enable_stdio_usb active */
  va_end(ap);
}

/* ---- plat_audio ---------------------------------------------------------- */
/* Non-blocking PWM beeper on GPIO11 (PIN_AUDIO).
 *
 * Frequency setup follows picosystem/libraries/hardware.cpp _play_note()
 * (lines 233-259):
 *   float pwm_divider = clock / AUDIO_PWM_WRAP / f;
 *   pwm_set_clkdiv(slice, pwm_divider);
 *   pwm_set_wrap(slice, AUDIO_PWM_WRAP);
 *   uint32_t max_count = (f * AUDIO_PWM_WRAP) / 10000;
 *   pwm_set_gpio_level(PIN_AUDIO, max_count / 2);   // 50% duty = full volume
 *
 * System clock: 250 MHz (overclock, hardware.cpp line 236 / plat_init above).
 *
 * Non-blocking: we record s_audio_stop_ms and silence in plat_poll_input
 * each frame, avoiding any blocking delay in the 30fps loop.
 */
void plat_audio(uint32_t freq_hz, uint32_t duration_ms) {
  if (freq_hz == 0 || duration_ms == 0) {
    pwm_set_gpio_level(PIN_AUDIO, 0);
    s_audio_stop_ms = 0;
    return;
  }

  const uint audio_slice = pwm_gpio_to_slice_num(PIN_AUDIO);

  /* Clock divider to achieve freq_hz with AUDIO_PWM_WRAP counter depth.
   * Reference: hardware.cpp _play_note lines 234-243 (250MHz path). */
  const float clock = 250000000.0F;
  const float divider = clock / (float)AUDIO_PWM_WRAP / (float)freq_hz;
  pwm_set_clkdiv(audio_slice, divider);
  pwm_set_wrap(audio_slice, AUDIO_PWM_WRAP);

  /* Duty cycle for full volume (50%): max_count follows hardware.cpp line 254.
   * We drive at max_count/2 for a clean square wave. */
  uint32_t max_count = (freq_hz * AUDIO_PWM_WRAP) / 10000U;
  if (max_count < 2U) {
    max_count = 2U;
  }
  pwm_set_gpio_level(PIN_AUDIO, max_count / 2U);

  /* Record when to silence — checked each frame in plat_poll_input. */
  s_audio_stop_ms = to_ms_since_boot(get_absolute_time()) + duration_ms;
}
